spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/tb_ecommerce_watch
   username: ra
   password: 12345
  jpa:
   properties:
    hibernate :
     dialect: org.hibernate.dialect.PostgreSQLDialect
   hibernate:  
    ddl-auto: update 